Repository PrograMemo-Groom/youtube-clone, pull requests merged in 2024-12, with the labels that each got.

#13 ✨ youtube API 추가
  .gitignore
  src/api/api.js
  src/api/endpoint.js
  src/components/main/Main.js
  src/config/config.js
  src/service/VideoService.js
Labels: 기능추가

#14 💄 assets 폴더 추가
  public/assets/dark/burger.svg
  public/assets/dark/makeVideo.svg
  public/assets/dark/mic.svg
  public/assets/dark/notice.svg
  public/assets/dark/search.svg
  public/assets/dark/youtubeLogo.svg
  public/assets/white/burger.svg
  public/assets/white/makeVideo.svg
  public/assets/white/mic.svg
  public/assets/white/notice.svg
  public/assets/white/search.svg
  public/assets/white/youtubeLogo.svg
Labels: 기능추가

#18 Header 부분 작업 완료
  src/components/header/Header.js
  src/components/header/Header.module.css
  src/hooks/useNavigation.js
Labels: Merge

#21 💄 main 카테코리 html/css 추가
  src/components/main/Main.js
  src/components/main/Main.module.css
Labels: Merge

#23 ✨동영상 상세 - creator-reserve-tap 테마 변경
  public/assets/icon/more_btn.svg
  src/App.js
  src/components/detail/Detail.css
  src/components/detail/Detail.js
  src/components/detail/creatorReserveTap/CreatorReserveTap.css
  src/components/detail/creatorReserveTap/CreatorReserveTap.js
  src/index.css
Labels: 기능추가

#24 🎨 search api result 결과값 확인
  src/App.js
  src/api/endpoint.js
  src/components/header/Header.js
  src/components/search/Search.js
  src/components/search/Search.module.css
  src/hooks/useNavigation.js
  src/service/VideoService.js
Labels: Merge

#26 Jkh
  public/assets/mypage/google-logo-icon.svg
  public/assets/mypage/profile-icon.svg
  public/assets/mypage/user-profile.png
  src/App.js
  src/components/myPage/MyPage.css
  src/components/myPage/MyPage.js
Labels: Merge

#29 🐛 Details 페이지 콘솔로그 잔뜩 뜨던거 해결, key값 문제였음
  src/components/detail/creatorReserveTap/CreatorReserveTap.js
Labels: 버그

#31 💄 메인페이지에 카테고리 부분 수정 + 사이드바 생성
  public/home.png
  public/mypage.png
  public/shorts.png
  public/subscription.png
  src/components/main/Main.js
  src/components/main/Main.module.css
  src/components/sidebar/Sidebar.js
  src/components/sidebar/Sidebar.module.css
Labels: 기능추가

#30 💄 스크롤 버튼 기능 추가
  src/components/detail/creatorReserveTap/CreatorReserveTap.css
  src/components/detail/creatorReserveTap/CreatorReserveTap.js
Labels: 기능추가

#32 ✨ 내 페이지: 임의 데이터로 배치 완료
  src/components/myPage/MyPage.css
  src/components/myPage/MyPage.js
Labels: Merge

#34 🎨 [구독] 유저 인증 및 사용자 구독 페이지 data 불러오는 로직 추가
  package-lock.json
  package.json
  src/App.js
  src/api/authApi.js
  src/api/endpoint.js
  src/components/Subscribe-demo.js
  src/config/config.js
  src/hooks/useGoogleAuth.js
  src/index.js
  src/service/VideoService.js
Labels: Merge

#35 💄 쇼츠 탭 화면 추가
  src/components/detail/Detail.js
  src/components/detail/creatorReserveTap/CreatorReserveTap.css
  src/components/detail/creatorReserveTap/CreatorReserveTap.js
  src/components/detail/shortsTap/ShortsTap.css
  src/components/detail/shortsTap/ShortsTap.js
  src/utils/formatViewerCount.js
Labels: 기능추가

#36 💄 쇼츠 탭, 관련 영상 탭
  src/App.js
  src/components/detail/Detail.js
  src/components/detail/creatorReserveTap/CreatorReserveTap.css
  src/components/detail/relatedVideo/RelatedVideo.css
  src/components/detail/relatedVideo/RelatedVideo.js
  src/components/detail/shortsTap/ShortsTap.css
  src/components/detail/shortsTap/ShortsTap.js
Labels: 기능추가

#37 💄 사이드바 assets 추가
  public/assets/dark/header/burger.svg
  public/assets/dark/header/makeVideo.svg
  public/assets/dark/header/mic.svg
  public/assets/dark/header/notice.svg
  public/assets/dark/header/search.svg
  public/assets/dark/header/youtubeLogo.svg
  public/assets/dark/sidebar/home.svg
  public/assets/dark/sidebar/home_select.svg
  public/assets/dark/sidebar/mypage.svg
  public/assets/dark/sidebar/mypage_select.svg
  public/assets/dark/sidebar/shorts.svg
  public/assets/dark/sidebar/shorts_select.svg
  public/assets/dark/sidebar/subscribe.svg
  public/assets/dark/sidebar/subscribe_select.svg
  public/assets/white/header/burger.svg
  public/assets/white/header/makeVideo.svg
  public/assets/white/header/mic.svg
  public/assets/white/header/notice.svg
  public/assets/white/header/search.svg
  public/assets/white/header/youtubeLogo.svg
  public/assets/white/sidebar/home.svg
  public/assets/white/sidebar/home_select.svg
  public/assets/white/sidebar/mypage.svg
  public/assets/white/sidebar/mypage_select.svg
  public/assets/white/sidebar/shorts.svg
  public/assets/white/sidebar/shorts_select.svg
  public/assets/white/sidebar/subscribe.svg
  public/assets/white/sidebar/subscribe_select.svg
  src/components/header/Header.js
Labels: Merge

#38 ✨구독 동영상 fetch코드 추가
  src/api/endpoint.js
  src/components/subscribe/Grid-subscribe.js
  src/components/subscribe/Grid-subscribe.module.css
  src/components/subscribe/Listed-subscribe.js
  src/components/subscribe/Listed-subscribe.module.css
  src/components/subscribe/Manage-subscribe.js
  src/components/subscribe/Manage-subscribe.module.css
  src/components/subscribe/Shorts-subscribe.js
  src/components/subscribe/Shorts-subscribe.module.css
  src/components/subscribe/service.js
Labels: Merge

#40 ✨ 내 페이지 반응형 ui로 변경
  src/components/myPage/MyPage.css
  src/components/myPage/MyPage.js
Labels: Merge

#43 Jkh
  src/components/myPage/MyPage.css
  src/components/myPage/MyPage.js
Labels: Merge

#45 💄 클래스 이름 소문자 변경
  package-lock.json
  src/App.js
  src/components/shorts/Panel.js
  src/components/shorts/Panel.module.css
  src/components/shorts/Shorts.js
  src/components/shorts/Shorts.module.css
  src/components/shorts/Video.js
  src/components/shorts/Video.module.css
  src/components/shorts/shorts.js
Labels: Merge

#47 💄 search video UI 구현
  public/assets/white/header/login.svg
  src/components/header/Header.js
  src/components/header/Header.module.css
  src/components/search/Search.js
  src/components/search/Search.module.css
Labels: Merge

#50 💄 메인 비디오, 비디오 설명란, 댓글창까지 하드코딩으로 구조 완료
  public/assets/icon/more_btn_black.svg
  src/components/detail/Detail.css
  src/components/detail/Detail.js
  src/components/detail/creatorReserveTap/CreatorReserveTap.css
  src/components/detail/creatorReserveTap/CreatorReserveTap.js
  src/components/detail/mainVideo/MainVideo.css
  src/components/detail/mainVideo/MainVideo.js
  src/components/detail/shortsTap/ShortsTap.js
Labels: 기능추가

#52 ✨ 카테고리별 페이지 나누기, '전체'카테고리 UI 구성
  public/avatar-1.png
  public/thumbnail-10.png
  src/App.js
  src/api/endpoint.js
  src/components/main/Main.js
  src/components/main/Main.module.css
  src/components/main/category/CategoryBar.js
  src/components/main/category/CategoryBar.module.css
  src/components/main/category/pages/Animation.js
  src/components/main/category/pages/Appreciate.js
  src/components/main/category/pages/Beauty.js
  src/components/main/category/pages/Comic.js
  src/components/main/category/pages/Cook.js
  src/components/main/category/pages/Custom.js
  src/components/main/category/pages/Game.js
  src/components/main/category/pages/Live.js
  src/components/main/category/pages/Mix.js
  src/components/main/category/pages/Music.js
  src/components/main/category/pages/News.js
  src/components/main/category/pages/Rap.js
  src/components/main/category/pages/Recently.js
  src/components/main/category/pages/Tour.js
  src/components/main/videos/MainVideos.js
  src/components/main/videos/MainVideos.module.css
  src/service/VideoService.js
Labels: Merge

#59 ✨ 동영상 상세 ui 간략하게 구현 완료 (더미데이터)
  src/components/detail/mainVideo/MainVideo.js
  src/components/detail/relatedVideo/RelatedVideo.js
  src/utils/formatTimeDifference.js
  src/utils/formatViewerCount.js
Labels: Merge

#68 💄 사이드바 버튼 클릭시 해당 페이지에 색상 변경되게 구현, 카테고리별 버튼 클릭시 렌더링되게 코드 변경
  src/components/main/Main.js
  src/components/main/category/CategoryBar.js
  src/components/main/videos/MainVideos.js
  src/components/sidebar/Sidebar.js
Labels: Merge

#69 💄 동영상 상세 페이지 다크모드
  src/components/context/context.js
  src/components/detail/Detail.css
  src/components/detail/Detail.js
  src/components/detail/creatorReserveTap/CreatorReserveTap.css
  src/components/detail/creatorReserveTap/CreatorReserveTap.js
  src/components/detail/mainVideo/MainVideo.css
  src/components/detail/mainVideo/MainVideo.js
  src/components/detail/relatedVideo/RelatedVideo.css
  src/components/detail/relatedVideo/RelatedVideo.js
  src/components/detail/shortsTap/ShortsTap.css
  src/components/detail/shortsTap/ShortsTap.js
  src/components/detail/themes/useThemeStyles.js
Labels: Merge

#71 Jkh
  .gitignore
  src/components/myPage/MyPage.css
  src/components/myPage/MyPage.js
  src/index.css
Labels: Merge, 할 일

#73 ✨ 마이페이지: 반응형 웹 수정, CSS 중복 코드 줄임
  src/components/myPage/MyPage.css
  src/components/myPage/MyPage.js
Labels: Merge

#75 💄manage페이지 ui 구현, CSS 다듬기(더미데이터)
  src/components/subscribe/Listed-subscribe.js
  src/components/subscribe/Manage-subscribe.module.css
  src/components/subscribe/Subscribe.js
  src/components/subscribe/grid/Grid-subscribe.js
  src/components/subscribe/grid/Grid-subscribe.module.css
  src/components/subscribe/list/Listed-subscribe.js
  src/components/subscribe/list/Listed-subscribe.module.css
  src/components/subscribe/manage/Manage-subscribe.js
  src/components/subscribe/manage/Manage-subscribe.module.css
  src/components/subscribe/shorts/Shorts-subscribe.js
  src/components/subscribe/shorts/Shorts-subscribe.module.css
  src/service/SubscribeService.js
Labels: Merge

#79 🚚 MainService 파일 생성 후 중복되는 동영상 기능 파일 나누기
  src/components/main/videos/MainVideos.js
  src/service/MainService.js
  src/service/VideoService.js
  src/utils/formatProfileImage.js
  src/utils/formatTimeDifference.js
  src/utils/formatVideoTime.js
  src/utils/formatViewPeople.js
Labels: Merge

#80 💄 마이페이지 UI 변경
  src/api/endpoint.js
  src/components/myPage/MyPage.css
Labels: Merge

#85 🎨 동영상 상세 페이지 api 데이터 적용 (메인 비디오, 설명탭, 댓글 갯수)
  src/components/detail/Detail.css
  src/components/detail/Detail.js
  src/components/detail/creatorReserveTap/CreatorReserveTap.css
  src/components/detail/mainVideo/MainVideo.js
  src/utils/getChannelSubscriberCount.js
Labels: Merge

#86 💄 mainVideo UI 추가 및 수정, 영상 호버 시 재생, 메인영상 클릭 시 detail페이지로 연결
  public/assets/videoMore/bookmark.svg
  public/assets/videoMore/clock.svg
  public/assets/videoMore/download.svg
  public/assets/videoMore/flag.svg
  public/assets/videoMore/no.svg
  public/assets/videoMore/none.svg
  public/assets/videoMore/playlist.svg
  public/assets/videoMore/share.svg
  public/assets/videoMore/wrong.svg
  public/avatar-1.png
  public/mypage.png
  public/shorts.png
  public/subscription.png
  public/thumbnail-10.png
  src/components/main/videos/MainVideos.js
  src/components/main/videos/MainVideos.module.css
  src/service/MainService.js
Labels: Merge

#87 🎨 더미데이터 -> api 데이터 , 메인비디오와 댓글 창까지 완료
  src/components/detail/creatorReserveTap/CreatorReserveTap.js
  src/components/detail/mainVideo/MainVideo.css
  src/components/detail/mainVideo/MainVideo.js
  src/components/detail/relatedVideo/RelatedVideo.js
  src/utils/fetchVideoComments.js
Labels: Merge

#88 💄shorts섹션 css 수정
  src/components/subscribe/grid/Grid-subscribe.js
  src/components/subscribe/grid/Grid-subscribe.module.css
  src/components/subscribe/list/Listed-subscribe.js
  src/components/subscribe/list/Listed-subscribe.module.css
  src/components/subscribe/shorts/Shorts-subscribe.js
  src/components/subscribe/shorts/Shorts-subscribe.module.css
Labels: Merge

#89 Jkh
  public/assets/mypage/playlist-icon.svg
  public/assets/mypage/video-later-view-icon.svg
  src/components/myPage/MyPage.css
  src/components/myPage/MyPage.js
Labels: Merge

#92 ♻️ searchVideo API 리팩토링 및 ⚡️ 성능 개선
  src/api/endpoint.js
  src/components/search/Search.js
  src/components/search/Search.module.css
  src/hooks/useIntersectionObserver.js
  src/service/SearchService.js
  src/service/VideoService.js
Labels: Merge

#99 Jkh
  src/components/myPage/MyPage.js
Labels: Merge

#101 💄 main 카테고리별 영상, 반응형
  src/components/main/Main.js
  src/components/main/category/CategoryAPI.js
  src/components/main/category/CategoryBar.js
  src/components/main/category/pages/Animation.js
  src/components/main/category/pages/Appreciate.js
  src/components/main/category/pages/Beauty.js
  src/components/main/category/pages/Comic.js
  src/components/main/category/pages/Cook.js
  src/components/main/category/pages/Custom.js
  src/components/main/category/pages/Game.js
  src/components/main/category/pages/Live.js
  src/components/main/category/pages/Mix.js
  src/components/main/category/pages/Music.js
  src/components/main/category/pages/News.js
  src/components/main/category/pages/Rap.js
  src/components/main/category/pages/Recently.js
  src/components/main/category/pages/Tour.js
  src/components/main/videos/MainVideos.js
  src/components/main/videos/MainVideos.module.css
  src/service/MainService.js
Labels: Merge

#107 🎨 사이드 탭 api 연동
  src/components/detail/Detail.js
  src/components/detail/creatorReserveTap/CreatorReserveTap.css
  src/components/detail/creatorReserveTap/CreatorReserveTap.js
  src/components/detail/creatorReserveTap/fetchCreatorVideos.js
  src/components/detail/relatedVideo/RelatedVideo.css
  src/components/detail/relatedVideo/RelatedVideo.js
Labels: Merge

#109 Jkh
  src/components/header/Header.module.css
  src/components/myPage/MyPage.css
  src/components/myPage/MyPage.js
  src/components/myPage/SortDropdown.css
Labels: Merge, 할 일

#110 🔀Merge branch 'kyr'
  src/components/subscribe/Subscribe.js
  src/components/subscribe/grid/Grid-subscribe.js
  src/service/SubscribeService.js
Labels: Merge

#111 💄 마이페이지: 드롭다운 백그라운드 컬러 수정
  src/components/myPage/SortDropdown.css
Labels: Merge

#112 💄 메인 프로필 사진 클릭 시 프로필 페이지 이동
  src/components/main/videos/MainVideos.js
  src/components/main/videos/MainVideos.module.css
  src/service/MainService.js
Labels: Merge

#113 ✨ 마이페이지: 기능 및 CSS 추가
  src/components/myPage/MyPage.css
  src/components/myPage/MyPage.js
  src/components/myPage/SortDropdown.css
Labels: Merge

#114 ✨ 무한 스크롤 기능 추가
  src/components/search/Search.js
  src/components/search/Search.module.css
  src/service/SearchService.js
Labels: Merge

#116 ✨ 매니지페이지/채널 리스트 api 연동
  src/components/subscribe/grid/Grid-subscribe.js
  src/components/subscribe/list/Listed-subscribe.js
  src/components/subscribe/manage/Manage-subscribe.js
  src/service/SubscribeService.js
Labels: Merge

#117 ✨ 마이페이지: 빈 재생목록 제거 및 데이터 추가 요청
  src/components/myPage/MyPage.css
  src/components/myPage/MyPage.js
Labels: Merge

#120 🎨 디테일 페이지 dialog 추가
  src/components/detail/Detail.css
  src/components/detail/Detail.js
  src/components/detail/creatorReserveTap/CreatorReserveTap.css
  src/components/detail/creatorReserveTap/CreatorReserveTap.js
  src/components/detail/mainVideo/MainVideo.css
  src/components/detail/mainVideo/MainVideo.js
  src/components/detail/relatedVideo/RelatedVideo.css
  src/components/detail/relatedVideo/RelatedVideo.js
  src/components/detail/shortsTap/ShortsTap.css
  src/components/detail/shortsTap/ShortsTap.js
Labels: Merge

#119 💄 메인 영상 프로필 연결 수정, 섬네일 크기 일치하게 조정
  src/components/main/category/CategoryBar.js
  src/components/main/videos/MainVideos.js
  src/components/main/videos/MainVideos.module.css
  src/service/MainService.js
Labels: Merge

#121 💄 mainVideo 더보기 모달 위치 수정
  src/components/detail/mainVideo/MainVideo.css
  src/components/detail/mainVideo/MainVideo.js
Labels: Merge

#122 ✨그리드페이지/쇼츠 섹션 로직 추가
  src/components/subscribe/grid/Grid-subscribe.js
  src/components/subscribe/grid/Grid-subscribe.module.css
  src/components/subscribe/list/Listed-subscribe.js
  src/components/subscribe/list/Listed-subscribe.module.css
  src/service/SubscribeService.js
  src/utils/fetchShortsVideos.js
Labels: Merge

#126 ✨인증토큰발급 헤더 버튼에서 가능하도록 수정
  src/components/header/Header.js
  src/components/subscribe/grid/Grid-subscribe.js
  src/components/subscribe/grid/Grid-subscribe.module.css
  src/components/subscribe/list/Listed-subscribe.js
  src/components/subscribe/list/Listed-subscribe.module.css
  src/components/subscribe/manage/Manage-subscribe.js
  src/service/SubscribeService.js
Labels: Merge

#127 ✨메인 영상 크기 동일하게, 무한 스크롤 기능 완료
  src/components/main/videos/MainVideos.js
  src/components/main/videos/MainVideos.module.css
  src/service/MainService.js
Labels: Merge

#128 💄메인 페이지 디자인 수정
  package-lock.json
  package.json
  src/components/detail/creatorReserveTap/CreatorReserveTap.css
  src/components/detail/creatorReserveTap/CreatorReserveTap.js
  src/components/detail/mainVideo/MainVideo.css
  src/components/detail/mainVideo/MainVideo.js
Labels: Merge

#129 ♻️ detail component 리팩토링
  src/components/detail/Detail.js
  src/components/detail/creatorReserveTap/CreatorReserveTap.js
  src/components/detail/mainVideo/MainVideo.js
  src/components/detail/mainVideo/comments/Comments.js
  src/components/detail/mainVideo/videoDetail/VideoDetail.js
  src/components/detail/mainVideo/videoPlayer/VideoPlayer.js
  src/components/detail/relatedVideo/RelatedVideo.js
  src/components/detail/shortsTap/ShortsTap.css
  src/components/detail/shortsTap/ShortsTap.js
  src/components/detail/shortsTap/fetchShortsVideos.js
  src/components/detail/shortsTap/shortsVideo/ShortsVideo.css
  src/components/detail/shortsTap/shortsVideo/ShortsVideos.js
  src/components/dropdownMenu/DropdownMenu.js
  src/utils/fetchCreatorVideos.js
Labels: Merge

#130 🎨 관련 동영상 탭 무한 스크롤
  package-lock.json
  package.json
  src/components/detail/Detail.js
  src/components/detail/creatorReserveTap/CreatorReserveTap.js
  src/components/detail/creatorReserveTap/videos/Videos.js
  src/components/detail/mainVideo/comments/Comments.js
  src/components/detail/relatedVideo/RelatedVideo.js
  src/components/detail/shortsTap/ShortsTap.js
  src/utils/fetchCreatorVideos.js
Labels: Merge

#131 ✨ 댓글탭 무한 스크롤
  src/components/detail/Detail.js
  src/components/detail/mainVideo/comments/Comments.js
  src/utils/fetchVideoComments.js
Labels: Merge

#132 :art: 주석처리해뒀던 relatedVideos 컴포넌트 주석제거
  src/components/detail/Detail.js
Labels: Merge

#133 ⚡️ redux 채용 후 리팩토링 완료
  package-lock.json
  package.json
  src/components/search/Search.js
  src/index.js
  src/store/Store.js
  src/store/actionType/SearchType.js
  src/store/actions/searchAction.js
  src/store/reducer/SearchReducer.js
Labels: 기능추가, 리팩토링

#134 ✨그리드, 리스트 페이지 커서 포인터 추가
  src/components/subscribe/grid/Grid-subscribe.js
  src/components/subscribe/grid/Grid-subscribe.module.css
  src/components/subscribe/list/Listed-subscribe.js
  src/components/subscribe/list/Listed-subscribe.module.css
  src/service/SubscribeService.js
Labels: Merge

#135 ✨ '더보기' 메뉴 클릭 시 확장된 사이드바 구현
  public/assets/sidebar/feedback.svg
  public/assets/sidebar/flag.svg
  public/assets/sidebar/game.svg
  public/assets/sidebar/help.svg
  public/assets/sidebar/history.svg
  public/assets/sidebar/later.svg
  public/assets/sidebar/learning.svg
  public/assets/sidebar/liked.svg
  public/assets/sidebar/live.svg
  public/assets/sidebar/logo.svg
  public/assets/sidebar/movie.svg
  public/assets/sidebar/music.svg
  public/assets/sidebar/playlist.svg
  public/assets/sidebar/podcast.svg
  public/assets/sidebar/settings.svg
  public/assets/sidebar/shop.svg
  public/assets/sidebar/sport.svg
  public/assets/sidebar/trending.svg
  public/assets/sidebar/videos.svg
  src/App.js
  src/components/header/Header.js
  src/components/sidebar/Sidebar.js
  src/components/sidebar/Sidebar.module.css
Labels: Merge

#136 ✨쇼츠페이지 api데이터 연결, 페이지 드롭다운 박스 추가
  src/components/subscribe/dropdown-menu/DropdownMenu.js
  src/components/subscribe/dropdown-menu/DropdownMenu.module.css
  src/components/subscribe/grid/Grid-subscribe.js
  src/components/subscribe/grid/Grid-subscribe.module.css
  src/components/subscribe/list/Listed-subscribe.js
  src/components/subscribe/list/Listed-subscribe.module.css
  src/components/subscribe/shorts/Shorts-subscribe.js
  src/components/subscribe/shorts/Shorts-subscribe.module.css
Labels: Merge

#137 ♻️api 데이터요청 부분 리덕스로 리팩토링, 페이지별 불필요 주석 삭제
  src/components/subscribe/grid/Grid-subscribe.js
  src/components/subscribe/list/Listed-subscribe.js
  src/components/subscribe/manage/Manage-subscribe.js
  src/store/Store.js
  src/store/actionType/SubscribeType.js
  src/store/actions/subscribeAction.js
  src/store/reducer/SubscribeReducer.js
Labels: Merge

#138 ➕ 리덕스 추가 및 리팩토링
  src/components/dropdownMenu/DropdownMenu.js
  src/components/dropdownMenu/DropdownMenu.module.css
  src/components/main/category/CategoryAPI.js
  src/components/main/category/CategoryBar.js
  src/components/main/videos/MainVideos.js
  src/components/main/videos/MainVideos.module.css
  src/components/sidebar/Sidebar.js
  src/service/MainService.js
  src/store/Store.js
  src/store/reducer/MainReducer.js
Labels: Merge

#139 🔥subscribe.js 삭제
  src/App.js
  src/components/subscribe/Subscribe.js
Labels: Merge

#141 디테일 페이지 리덕스 병합용
  src/components/detail/Detail.js
  src/components/detail/creatorReserveTap/CreatorReserveTap.js
  src/components/detail/creatorReserveTap/videos/Videos.js
  src/components/detail/mainVideo/MainVideo.js
  src/components/detail/mainVideo/comments/Comments.js
  src/components/detail/mainVideo/videoDetail/VideoDetail.js
  src/components/detail/mainVideo/videoPlayer/VideoPlayer.js
  src/components/detail/relatedVideo/RelatedVideo.js
  src/components/detail/shortsTap/ShortsTap.js
  src/service/detailService.js
  src/store/Store.js
  src/store/actionType/DetailType.js
  src/store/actions/DetailActions.js
  src/store/reducer/detailReducer.js
  src/utils/fetchVideoComments.js
Labels: Merge

#142 💡주석 처리한 컴포넌트 제거
  src/components/detail/Detail.js
Labels: Merge
